# conda env remove -n ml
# conda env create -f environments.yaml

# For Mac
name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy==1.26.4
  - faiss-cpu
  - matplotlib==3.10.1
  - seaborn==0.13.2
  - scikit-learn==1.6.1
  - tqdm==4.67.1
  - psutil==7.0.0
  - pip:
      - torch==2.6.0
      - accelerate==0.27.2
      - transformers==4.50.3
      - datasets==2.17.1
      - sentence-transformers==3.4.1
      - langchain==0.1.15
      - langchain-core==0.1.41
      - langchain-community
      - langchainhub
      - chromadb==1.0.5
      - captum==0.8.0
      - ragas==0.2.14
      - openai
      - nest_asyncio
      - lime==0.2.0.1
      - shap==0.44.0
      - rank_bm25
      - jupyter
  
 
# - peft==0.10.0
# - trl==0.8.6
# - bitsandbytes==0.45.5
